"""Adding front_id column to manuscript node

Revision ID: 0e56df635823
Revises: 8ad9a7aa6565
Create Date: 2026-03-27 19:17:27.161990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e56df635823'
down_revision: Union[str, None] = '8ad9a7aa6565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manuscript_nodes', sa.Column(
        'front_id',
        sa.UUID(),
        nullable=False,
        server_default=sa.text("gen_random_uuid()"),
    ))
    op.create_index(op.f('ix_manuscript_nodes_front_id'), 'manuscript_nodes', ['front_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manuscript_nodes_front_id'), table_name='manuscript_nodes')
    op.drop_column('manuscript_nodes', 'front_id')
    # ### end Alembic commands ###
