"""replace chat_messages and chat_tool_calls with chat_events

Revision ID: 0f4deba1db95
Revises: edb2ac8c769c
Create Date: 2026-03-30 16:43:46.163106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f4deba1db95'
down_revision: Union[str, None] = 'edb2ac8c769c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=255), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('tool_args', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_events_conversation_id'), 'chat_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_events_id'), 'chat_events', ['id'], unique=False)
    op.drop_index('ix_chat_messages_conversation_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_tool_call_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_chat_tool_calls_conversation_id', table_name='chat_tool_calls')
    op.drop_index('ix_chat_tool_calls_id', table_name='chat_tool_calls')
    op.drop_table('chat_tool_calls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_tool_calls',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('chat_tool_calls_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tool', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('args', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('called_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'''completed'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('llm_tool_call_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ai_message_dump', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='chat_tool_calls_conversation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_tool_calls_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_chat_tool_calls_id', 'chat_tool_calls', ['id'], unique=False)
    op.create_index('ix_chat_tool_calls_conversation_id', 'chat_tool_calls', ['conversation_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('emit_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tool_call_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='chat_messages_conversation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_call_id'], ['chat_tool_calls.id'], name='chat_messages_tool_call_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='chat_messages_pkey')
    )
    op.create_index('ix_chat_messages_tool_call_id', 'chat_messages', ['tool_call_id'], unique=False)
    op.create_index('ix_chat_messages_id', 'chat_messages', ['id'], unique=False)
    op.create_index('ix_chat_messages_conversation_id', 'chat_messages', ['conversation_id'], unique=False)
    op.drop_index(op.f('ix_chat_events_id'), table_name='chat_events')
    op.drop_index(op.f('ix_chat_events_conversation_id'), table_name='chat_events')
    op.drop_table('chat_events')
    # ### end Alembic commands ###
