"""add last_vectorized_at to books

Revision ID: 1ba0dfa35241
Revises: 0f4deba1db95
Create Date: 2026-03-30 20:57:37.419221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba0dfa35241'
down_revision: Union[str, None] = '0f4deba1db95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('last_vectorized_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'last_vectorized_at')
    # ### end Alembic commands ###
