"""New column ia-settings for books

Revision ID: 3e09a10c7a1c
Revises: 6a35bf5ea9b4
Create Date: 2026-04-04 20:32:24.835491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e09a10c7a1c'
down_revision: Union[str, None] = '6a35bf5ea9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('ia_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'ia_settings')
    # ### end Alembic commands ###
