"""Addding books commit and manuscript snapshot to database for history management

Revision ID: 406e943bcb22
Revises: 8fcffaa0c5a2
Create Date: 2026-03-29 10:09:53.159223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406e943bcb22'
down_revision: Union[str, None] = '8fcffaa0c5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_commits_book_id'), 'book_commits', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_commits_id'), 'book_commits', ['id'], unique=False)
    op.create_table('manuscript_node_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commit_id', sa.Integer(), nullable=False),
    sa.Column('front_id', sa.UUID(), nullable=False),
    sa.Column('parent_front_id', sa.UUID(), nullable=True),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('is_numbered', sa.Boolean(), nullable=False),
    sa.Column('depth_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['book_commits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscript_node_snapshots_commit_id'), 'manuscript_node_snapshots', ['commit_id'], unique=False)
    op.create_index(op.f('ix_manuscript_node_snapshots_id'), 'manuscript_node_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manuscript_node_snapshots_id'), table_name='manuscript_node_snapshots')
    op.drop_index(op.f('ix_manuscript_node_snapshots_commit_id'), table_name='manuscript_node_snapshots')
    op.drop_table('manuscript_node_snapshots')
    op.drop_index(op.f('ix_book_commits_id'), table_name='book_commits')
    op.drop_index(op.f('ix_book_commits_book_id'), table_name='book_commits')
    op.drop_table('book_commits')
    # ### end Alembic commands ###
