"""Adding manuscript node + series to book

Revision ID: 83915ffc0005
Revises: f8c8e5cf33df
Create Date: 2026-03-27 11:45:26.531418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83915ffc0005'
down_revision: Union[str, None] = 'f8c8e5cf33df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_id'), 'series', ['id'], unique=False)
    op.create_index(op.f('ix_series_user_id'), 'series', ['user_id'], unique=False)
    op.create_table('manuscript_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('is_numbered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['manuscript_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscript_nodes_book_id'), 'manuscript_nodes', ['book_id'], unique=False)
    op.create_index(op.f('ix_manuscript_nodes_id'), 'manuscript_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_manuscript_nodes_parent_id'), 'manuscript_nodes', ['parent_id'], unique=False)
    op.add_column('books', sa.Column('series_id', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('parent_book_id', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('position_in_series', sa.Float(), nullable=True))
    op.add_column('books', sa.Column('is_spinoff', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('books', 'genre',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_books_series_id'), 'books', ['series_id'], unique=False)
    op.create_foreign_key(None, 'books', 'books', ['parent_book_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'books', 'series', ['series_id'], ['id'], ondelete='SET NULL')
    op.drop_column('books', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, server_default="''"))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_series_id'), table_name='books')
    op.alter_column('books', 'genre',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('books', 'is_spinoff')
    op.drop_column('books', 'position_in_series')
    op.drop_column('books', 'parent_book_id')
    op.drop_column('books', 'series_id')
    op.drop_index(op.f('ix_manuscript_nodes_parent_id'), table_name='manuscript_nodes')
    op.drop_index(op.f('ix_manuscript_nodes_id'), table_name='manuscript_nodes')
    op.drop_index(op.f('ix_manuscript_nodes_book_id'), table_name='manuscript_nodes')
    op.drop_table('manuscript_nodes')
    op.drop_index(op.f('ix_series_user_id'), table_name='series')
    op.drop_index(op.f('ix_series_id'), table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
