"""Adding node manuscript depth level

Revision ID: 8ad9a7aa6565
Revises: 83915ffc0005
Create Date: 2026-03-27 14:34:00.695213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad9a7aa6565'
down_revision: Union[str, None] = '83915ffc0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manuscript_nodes', sa.Column('depth_level', sa.Integer(), nullable=False, server_default="2"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manuscript_nodes', 'depth_level')
    # ### end Alembic commands ###
