"""Adding tool call message to conversation (to persist tool calls)

Revision ID: 8fcffaa0c5a2
Revises: ba8d696cdca5
Create Date: 2026-03-28 16:03:38.831104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fcffaa0c5a2'
down_revision: Union[str, None] = 'ba8d696cdca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=100), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('called_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_tool_calls_conversation_id'), 'chat_tool_calls', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_tool_calls_id'), 'chat_tool_calls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_tool_calls_id'), table_name='chat_tool_calls')
    op.drop_index(op.f('ix_chat_tool_calls_conversation_id'), table_name='chat_tool_calls')
    op.drop_table('chat_tool_calls')
    # ### end Alembic commands ###
