"""Replacing parent_id with parent_front_id

Revision ID: ba8d696cdca5
Revises: 0e56df635823
Create Date: 2026-03-27 20:08:50.217825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8d696cdca5'
down_revision: Union[str, None] = '0e56df635823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manuscript_nodes', sa.Column('parent_front_id', sa.UUID(), nullable=True))
    op.drop_index('ix_manuscript_nodes_parent_id', table_name='manuscript_nodes')
    op.create_index(op.f('ix_manuscript_nodes_parent_front_id'), 'manuscript_nodes', ['parent_front_id'], unique=False)
    op.drop_constraint('manuscript_nodes_parent_id_fkey', 'manuscript_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'manuscript_nodes', 'manuscript_nodes', ['parent_front_id'], ['front_id'], ondelete='SET NULL')
    op.drop_column('manuscript_nodes', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manuscript_nodes', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'manuscript_nodes', type_='foreignkey')
    op.create_foreign_key('manuscript_nodes_parent_id_fkey', 'manuscript_nodes', 'manuscript_nodes', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_manuscript_nodes_parent_front_id'), table_name='manuscript_nodes')
    op.create_index('ix_manuscript_nodes_parent_id', 'manuscript_nodes', ['parent_id'], unique=False)
    op.drop_column('manuscript_nodes', 'parent_front_id')
    # ### end Alembic commands ###
