"""Adding hitl_columns

Revision ID: edb2ac8c769c
Revises: 406e943bcb22
Create Date: 2026-03-29 23:15:08.645694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb2ac8c769c'
down_revision: Union[str, None] = '406e943bcb22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('tool_call_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_messages_tool_call_id'), 'chat_messages', ['tool_call_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'chat_tool_calls', ['tool_call_id'], ['id'], ondelete='SET NULL')
    op.add_column('chat_tool_calls', sa.Column('status', sa.String(length=30), nullable=False, server_default="'completed'"))
    op.add_column('chat_tool_calls', sa.Column('llm_tool_call_id', sa.String(length=255), nullable=True))
    op.add_column('chat_tool_calls', sa.Column('ai_message_dump', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_tool_calls', 'ai_message_dump')
    op.drop_column('chat_tool_calls', 'llm_tool_call_id')
    op.drop_column('chat_tool_calls', 'status')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_tool_call_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'tool_call_id')
    # ### end Alembic commands ###
